# MODEL INFORMATION
model: "llama3.1"
custom_model: "urbaniste"

# TASK
task: "annotation" # "annotation" or "extraction"

# PATH-RELATED INFORMATION
root_dir_path: "/Users/valentinefleith/Perso/code/urbanism-annotation-llm"
csv_corpus_path: "corpus/corpus_phrases/corpus_test"
model_annotations_save_path: "annotations/annotations_llm/promptv1"
results_save_path: "results/classification/promptv1"

# BOOLEAN INFORMATION
save_annotations: false
skip_already_annotated: false
save_result_metrics: true
save_result_matrices: false
